name: BioClocksClass
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - R=3.6
  - mpi4py=3.0.3
  # - openmpi=4.0.2
  - numpy=1.16
  - pandas=0.24
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - configobj=5.0
  - mpmath=1.1
  - ipython
  - seaborn
  - pip
  - jupyterlab
  - nb_conda_kernels
  - ipykernel
  - nodejs
  - ipycytoscape
  - pip:
      - -e src/pydl
      - -e src/pyjtk
